package de.codekenner.practiceschedule.data.remote

internal class AuthSuccessError : Throwable()
